### ISSUE TITLE
Supporting a subset of imports

### ISSUE THREAD

**Issue by Raynos** [uber/thriftrw-node#57]
There was discussion around using imports to import "common types"

Currently `thriftrw` does not support imports.

It would be nice if we can implement imports.

### Import strict mode

In the same vain as the rest of `thriftrw`; It would be nice to have a "subset of thrift" for the strict mode.

For example if strict is true we could only allow `import` statements if the file being imported does not have any `service` definition.

This allows us to statically avoid the "anti-pattern" of importing types from other services.

cc @kriskowal @malandrew @IvanMalison @rssathe

**Comment by kriskowal** [comment]
We also haven’t yet supported extending services, structs, and exceptions. This policy would preclude extending an “abstract” service.

**Comment by Raynos** [comment]
We can add more features to strict mode in the future. 

The value in strict mode is picking a subset of features we have consensus on and adding more features once we have more consensus.

**Comment by Raynos** [comment]
That being said; We have no consensus on what a sensible subset on import semantics are. We should discuss this more. I only intend to start the discussion.

**Comment by kriskowal** [comment]
Fixed by #85

**Comment by Raynos** [comment]
NOICE.
